base:
    serial_number: "v1" # 版本号
    service_name: "caoguo" # 服务名
    service_displayname: "caoguo" # 服务显示名
    sercice_desc: "caoguo" # 描述
    is_dev: true
mysql_info:
    port : 3306 # 端口号
    username : root # 用户名
    host :  localhost # 地址
    password : 123456 # 密码
    # host : localhost
    # password : qwer
    database : caoguo_dev # 数据库名
kdniao: # 快递鸟配置
    business_id : 1317777
    app_key : 111111-2222-3333-4444-555555555
email: # 发邮件配置
    user: xie1xiao1jun@126.com
    password: pppppppppppppp
    host: smtp.126.com:25
wx_info: # 微信相关配置
    app_id : wxc111111111111
    app_secret : 111111111111111111111
    api_key : 1111111111111111111111111
    mch_id : 1111111111111111
    notify_url : http://www.xxjwxc.cn
    shear_url : ""
file_host: https://localhost/commcn/api/v1
oauth2_url: http://localhost/oauth2/api/v1
register_url: http://localhost/register/api/v1
token_type: nomal
app_id: wwwthings
app_secret: 4EE0A9A43B9B911C067BEE5CC50A9972
port : 8001